// <auto-generated />
using System;
using EEFCORECLI.MODEL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreCLI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200419130013_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCORECLI.MODEL.Schema.HocPhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("HocPhan");
                });

            modelBuilder.Entity("EFCORECLI.MODEL.Schema.LopHocPhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdHocPhan")
                        .HasColumnType("int");

                    b.Property<string>("MSSV")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdHocPhan");

                    b.HasIndex("MSSV");

                    b.ToTable("LopHocPhan");
                });

            modelBuilder.Entity("EFCORECLI.MODEL.Schema.SinhVien", b =>
                {
                    b.Property<string>("MSSV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("MSSV");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("EFCORECLI.MODEL.Schema.LopHocPhan", b =>
                {
                    b.HasOne("EFCORECLI.MODEL.Schema.HocPhan", "HocPhan")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("IdHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCORECLI.MODEL.Schema.SinhVien", "SinhVien")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MSSV");
                });
#pragma warning restore 612, 618
        }
    }
}
